language: python

matrix:
  include:
    - os: linux
      python: 2.7
      sudo: required
      env:
        - TOXENV=python2.7

    - os: linux
      python: 3.4
      sudo: required
      env:
        - TOXENV=python3.4

    - os: linux
      python: 3.5
      sudo: required
      env:
        - TOXENV=python3.5

    - os: linux
      python: 3.6
      sudo: required
      env:
        - TOXENV=python3.6
        - DEPLOY_FILE='dist/sqlitebiter_*.deb'

    - os: linux
      python: 3.7-dev
      sudo: required
      env: TOXENV=python3.7

    - os: osx
      language: generic
      env:
        - TOXENV=python3.6
        - DEPLOY_FILE='dist/sqlitebiter_macos_*'

install:
  - bash .travis/install.sh

script: 
  - tox

notifications:
  slack:
    secure: EHpNEhPxWbvByJouszVg5JIU9BBURFQnHlMEJDudWnK8i0hF37OYKkC8oSbvi2Hz+/bCW4eFStwuTu17RA9diUI6F4ZQ+H0OygI5NqlGSlty0sQpfpxOTSVlqGupKJtZRG5yeqzCVEdXYLZOQH8q54yUADxpjaPkdvCoOrcPB/xBe8vxpUc4uPtYQVeCJCOij0y+3nEwOOu/A8JBk0Uhx9690qKHzYwv3V93M4OjYeWntEcmcbJaLj+BCVV+DT3rPoUeweoZHwd/0euyKR/NmjR/y0uIsIkcjKpwDACaPIzzoQUD7VMf+91yebqI42t5ukg4fDArGE8jkQrRPsTKBdBP7n32n8PShWVypXR/CN/qYZvWwoVkuyYp2KudJIXm9SzWuW0sYjL4BaI9/sQs8iZfXOW2UJfErwNn5gybkxc/59hgtR955ceYWjKSm++KzG9AYb3c7MqY2HHWGdGxNHD6dv2tnTQJ1FUNC5wuOwmOsg0EjHD+o67zYuvOOsjA2EfgjFVqsWLBy7Uh9fQVBOUpb3NCFA0ZDK02xaBtuZSzhT2vCviUkRsvgIy51yzPt6ldeadKtogCUKrQU3U9M0R3ZkoJSZaN74ZHA33IFtCKfnIkZaoJ1w+DRGPLw8D31CI/dxIoeVUjsCYhDuPLxcF/L1x5GS/8tJHXcZEGK/c=

before_deploy:
  - bash -x build_package.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "RZIH5nHpf0NxOSpxw0RVgrd0V+JkChHJVrv1Jsz6ix6KIzpA6SoyF1L8PviBB69Fp4NFaoyjlhqhOgNjNB0wZ90olYHijY+MliMkrt45rNqCdZrZoqJa9ccVt1ZvB6jP//2sS90n0GyVeXcmf+8esrQDhZ+bh1/RP70Q8ZyRom6z/qa3oIE4BF8GpspnGeyVZ27GAWSltkhxrW84oNbX9aBaASRYYTP+Qr+Chb0kHlZzrME65UeNndaT+p77ZtwK4Z6qpzvhb6utFe4eYk1HYlsEN23FgFikAceB4zxcayAyd04cfG6+a2kECw3kvc1hNGCTad/4LHj+j7N+YDw2DrPE5hcXPdf7S8e/fKguwTJrw5DNkCei9KNKij9ZFANDwH7HlptCCLHGXMpU76KgpWYDI35YHiEFOC4vxoBUHL7KUTH4RscwJE48kZVscG+BgUZRvzx6rwy5pyUSOHusbYg8b1QEhplp6uaVG6HqUD0SMQylVT42ZPZQIABFVt0WnMuzq6EFazeehvPfa85iX51DNJiSMdmlWnAXj7NLJagV/bvsyarpcfmRuHtF9y3vJww8+J9UBUZoMQzgAGVQFzm775TwzwhOIfTHEZ+jq1FIKouLm5Y38s8K8EbVNujiHdCHx1UDqi8KSQ7TZUPj376UuaeGoaMRZPtUK1G7Owo="
  file_glob: true
  file: $DEPLOY_FILE
  on:
    tags: true
    condition: "$TOXENV = python3.6"
