language: python

matrix:
  include:
    - os: linux
      python: 2.7
      sudo: required
      env:
        - TOXENV=python2.7

    - os: linux
      python: 3.4
      sudo: required
      env:
        - TOXENV=python3.4

    - os: linux
      python: 3.5
      sudo: required
      env:
        - TOXENV=python3.5

    - os: linux
      python: 3.6
      sudo: required
      env:
        - TOXENV=python3.6
        - DEPLOY_FILE='dist/sqlitebiter_*.deb'

    - os: osx
      language: generic
      env:
        - TOXENV=python3.6
        - DEPLOY_FILE='dist/sqlitebiter_macos_*'

install:
  - bash .travis/install.sh

script: 
  - tox

notifications:
  slack:
    secure: EHpNEhPxWbvByJouszVg5JIU9BBURFQnHlMEJDudWnK8i0hF37OYKkC8oSbvi2Hz+/bCW4eFStwuTu17RA9diUI6F4ZQ+H0OygI5NqlGSlty0sQpfpxOTSVlqGupKJtZRG5yeqzCVEdXYLZOQH8q54yUADxpjaPkdvCoOrcPB/xBe8vxpUc4uPtYQVeCJCOij0y+3nEwOOu/A8JBk0Uhx9690qKHzYwv3V93M4OjYeWntEcmcbJaLj+BCVV+DT3rPoUeweoZHwd/0euyKR/NmjR/y0uIsIkcjKpwDACaPIzzoQUD7VMf+91yebqI42t5ukg4fDArGE8jkQrRPsTKBdBP7n32n8PShWVypXR/CN/qYZvWwoVkuyYp2KudJIXm9SzWuW0sYjL4BaI9/sQs8iZfXOW2UJfErwNn5gybkxc/59hgtR955ceYWjKSm++KzG9AYb3c7MqY2HHWGdGxNHD6dv2tnTQJ1FUNC5wuOwmOsg0EjHD+o67zYuvOOsjA2EfgjFVqsWLBy7Uh9fQVBOUpb3NCFA0ZDK02xaBtuZSzhT2vCviUkRsvgIy51yzPt6ldeadKtogCUKrQU3U9M0R3ZkoJSZaN74ZHA33IFtCKfnIkZaoJ1w+DRGPLw8D31CI/dxIoeVUjsCYhDuPLxcF/L1x5GS/8tJHXcZEGK/c=

before_deploy:
  - bash -x build_package.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KMCOwxbBbEdh8vQl6sikAK+11xN3Zh5mHUyIbcD/nQK9rJlMXXBQ5vrhbr/Ybe8/JAUI1IX33PzUM4dK0oycdnvuKD10i2knV7pJHUEf+ykoijNE7RV/6hh068Cda4l86z74H3r8DfvxbgcpwtwwyHbWQa/j0s5jKg/sPcWv39m8F8t77pEJOvvjhCmoPTdtKUZg/HcXJmYLPXsvZjfNh6SncN2CtJ8o1CmUCh+BMpMBCdt8N3YOzdQEsDTQEk+CnrAuizSn33g3RBt8VrlN+HSOoK7sqba8nnLDhz5AO0qi2HeZOMr71JXInEEFOnjpdkhQaT+oRlPtIEVg8EU7m9FBuNAzkcDJF/1rFKWmczaGD1B+BEqBgnLl+0pN2EApD0QodIXOWg81+qgVOh8besdCwJ+d2NOpBKqR94jrr8SY18JCei49iqsJuaRWrWcrnl1MaGqfj1BFVLqAmTxB4ajizFEfAap/T3Nxs+AvPpP0r9vGx24W5MpsPrdmU8zZlgIlnl35pMhN/PP6OBjoS0yFWZSjASTuCANE9pxIeXlhciVaWUJ1Urmi5/q+tWNUJnXN9hoOz8ZJihgvf91vrTq63VA8NCYVxcABbY94aZY78p4CeiP9oCGQWBhzXszQzOBme8eC5nNna8NuCASvUp8RByc6pprcpZWMx7aMDKc=
  file_glob: true
  file: $DEPLOY_FILE
  on:
    tags: true
    branch: master
    condition: "$TOXENV = python3.6"
