language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.3
      env: TOXENV=python3.3
    - python: 3.4
      env: TOXENV=python3.4
    - python: 3.5
      env: TOXENV=python3.5
    - python: 3.6
      env: TOXENV=python3.6

os:
  - linux

install:
  - pip install tox

script: 
  - tox

notifications:
  slack:
    secure: EHpNEhPxWbvByJouszVg5JIU9BBURFQnHlMEJDudWnK8i0hF37OYKkC8oSbvi2Hz+/bCW4eFStwuTu17RA9diUI6F4ZQ+H0OygI5NqlGSlty0sQpfpxOTSVlqGupKJtZRG5yeqzCVEdXYLZOQH8q54yUADxpjaPkdvCoOrcPB/xBe8vxpUc4uPtYQVeCJCOij0y+3nEwOOu/A8JBk0Uhx9690qKHzYwv3V93M4OjYeWntEcmcbJaLj+BCVV+DT3rPoUeweoZHwd/0euyKR/NmjR/y0uIsIkcjKpwDACaPIzzoQUD7VMf+91yebqI42t5ukg4fDArGE8jkQrRPsTKBdBP7n32n8PShWVypXR/CN/qYZvWwoVkuyYp2KudJIXm9SzWuW0sYjL4BaI9/sQs8iZfXOW2UJfErwNn5gybkxc/59hgtR955ceYWjKSm++KzG9AYb3c7MqY2HHWGdGxNHD6dv2tnTQJ1FUNC5wuOwmOsg0EjHD+o67zYuvOOsjA2EfgjFVqsWLBy7Uh9fQVBOUpb3NCFA0ZDK02xaBtuZSzhT2vCviUkRsvgIy51yzPt6ldeadKtogCUKrQU3U9M0R3ZkoJSZaN74ZHA33IFtCKfnIkZaoJ1w+DRGPLw8D31CI/dxIoeVUjsCYhDuPLxcF/L1x5GS/8tJHXcZEGK/c=

deploy:
  provider: pypi
  user: vmmhypervisor
  password:
    secure: G5oFtkhgK1EV5WCnFi3JwbMDxOGriejRZ0tuM8cUPlM+mE52VP1rjCqschM5DlU13cN4UUTY+KsxsHkTZqW+Yb4cAnRHn/LXBNl77xNC3jRXFJeUQXpk3NWj+rUI4wzK5/9haIyw0REUT7JN+FnS56gcX56aIMBo+PDgBWD3HmzunM0jltbUdQ2eKd5OaqQbmNh8+H6cIXbDTzuuT/e1m+PqRJ5BLxguPwzyN3TDkpqVe7Uo0g76oK3hGJfMAsFtWTW6jVFTTom61lmUcapU/Ye8utSH5jK7CTlK15T7FrPdV+eKIDPFGWgKx5TyazT6fJVz3EZmsAfIUsD9UEJ7CaBtQlejscb7tT/qf9vt5cWJNb6je7cRdcYQbFmnCJYSckQm0WlRMWxr7tSAEICzdL4Hqi1ZXLT76zEGcRF+qdHK0v67b//bIzQ37jU6ebkhOb/cTUL4e275WbfZRaldqQsLQcIqOVZZoVBIQjNTL/h7ni3PrEun1e4OnvUGuA62UX/nbCr/qqnvf95U6MvEOTAF6Hb/j2NRlZW5VPvScZEmMWjc1lINW3ze/Srud4AEdlC0/C5FbhrIg+CMDOQmTVwRRRVvxANJN622bf2tMz30uALdXkv5VvuExgzajZfAOyyDl+hTIx/T/2KBFPhI0na5JYObWXhZs/AhPD3klxY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    branch: master
  distributions: "sdist bdist_wheel"
